// src/types/index.ts

/** All parliamentary group codes for the 17e legislature. */
export const GROUP_CODES = [
  "LFI", "GDR", "ECO", "SOC", "LIOT",
  "EPR", "DEM", "HOR", "DR", "UDR", "RN",
] as const;
export type GroupCode = typeof GROUP_CODES[number];

/** Thematic buckets used by the deck composer to enforce diversity (V2).
 *  "autre" is the catch-all for votes that don't fit a major 2027 theme. */
export const THEMES = [
  "pouvoir-achat", "retraites", "immigration", "sécurité", "écologie",
  "santé", "école", "fiscalité", "institutions", "international", "autre",
] as const;
export type Theme = typeof THEMES[number];

/** Position taken by a parliamentary group on a single scrutin. */
export type GroupPosition = "pour" | "contre" | "abstention" | "divisé";

/** User's choice on a single scrutin. */
export type UserVote = "pour" | "contre" | "skip";

/** Raw vote breakdown for a group on a scrutin. */
export interface GroupVoteBreakdown {
  pour: number;
  contre: number;
  abstention: number;
  absent: number;  // non-votants
}

/** A scrutin as stored in the database and consumed by the front. */
export interface Scrutin {
  id: string;                  // ex: "VTANR5L17V1234"
  numero: number;
  date: string;                // ISO yyyy-mm-dd
  dossier_id: string;
  dossier_titre: string;
  chapeau: string;             // "RETRAITES · PLFSS 2024"
  titre_brut: string;          // raw AN title
  titre_pedago: string;        // 12-word generated summary
  contexte?: string;           // 1-line stake/context, ≤ 25 words (added in migration 0002)
  analyse_loi?: ScrutinAnalyse;  // structured 4-axis breakdown (migration 0003).
                                 // Column named `analyse_loi` because ANALYSE
                                 // is a PostgreSQL reserved word.
  points_cles?: string[];        // exactly 3 short factual bullets, 7 words
                                 // max each, shown on the card front below
                                 // the titre_pedago (migration 0004).
  theme?: Theme;                 // thematic bucket used by the deck composer
                                 // to enforce diversity (migration 0005).
  position_par_groupe: Record<GroupCode, GroupPosition>;
  votes_bruts: Record<GroupCode, GroupVoteBreakdown>;
  url_an_officielle: string;
  est_solennel: boolean;
  pedago_relu: boolean;
}

/** A single user vote on a scrutin during a session. */
export interface SessionVote {
  scrutin_id: string;
  choice: UserVote;
  voted_at: number;  // epoch ms
}

/** Persistent session shape in localStorage. */
export interface SessionState {
  session_id: string;
  cards_seen: string[];        // scrutin ids in order
  votes: SessionVote[];
  started_at: number;          // epoch ms
}

/** Structured analyse — 4-axis factual breakdown of what a law actually does.
 *  Generated by the LLM during ingestion, exposed via the "+ analyse"
 *  bottom-sheet on the card. All arrays may be empty; **bold** markdown
 *  markers are supported (rendered via renderWithBold helper). */
export interface ScrutinAnalyse {
  mesures_principales: string[];      // what the law creates / forbids / changes
  concernes_positifs: string[];       // groups/sectors with positive impact
  concernes_negatifs: string[];       // groups/sectors with negative impact
  concernes_neutres: string[];        // groups/sectors with mixed or to-watch impact
  calendrier: string[];               // dates: entry into force, intermediate steps
  exceptions: string[];               // exemptions, derogations, transitions
}

/** Per-group alignment result. */
export interface GroupAlignment {
  group: GroupCode;
  pct: number;                 // 0..100, rounded
  counted: number;             // scrutins where group not "divisé" and user not "skip"
  perfect: number;             // exact match count
  partial: number;             // pour/abstention or contre/abstention
  conflict: number;            // pour/contre
  divided_excluded: number;    // scrutins where group was "divisé" (not counted)
}

/** Freshness metadata of the database. */
export interface FreshnessInfo {
  total_scrutins: number;
  last_sync_at: string;        // ISO datetime
  next_sync_eta: string;       // ISO datetime
}
