-- supabase/migrations/0002_add_contexte.sql
--
-- Add a short context line shown under the pedagogical title on cards.
-- Generated by the LLM during ingestion (or by the truncation fallback).
-- One sentence, ≤ 25 words, accessible to a high schooler — answers
-- "qu'est-ce qui est en jeu derrière ce vote".

alter table scrutins
  add column if not exists contexte text;
