-- supabase/migrations/0003_add_analyse.sql
--
-- Add a structured "analyse" jsonb column to scrutins. Six string[] arrays
-- (mesures_principales, concernes_positifs, concernes_negatifs,
-- concernes_neutres, calendrier, exceptions) generated by the LLM during
-- ingestion. Powers the "+ analyse" bottom-sheet on the card front.
--
-- Existing rows have NULL until the next `npm run ingest:an` run.

alter table scrutins
  add column if not exists analyse jsonb;
