-- supabase/migrations/0003_add_analyse.sql
--
-- Add a structured analyse_loi jsonb column to scrutins. Six string[] arrays
-- (mesures_principales, concernes_positifs, concernes_negatifs,
-- concernes_neutres, calendrier, exceptions) generated by the LLM during
-- ingestion. Powers the "+ analyse" card overlay.
--
-- NOTE: the column is named `analyse_loi`, not `analyse`, because ANALYSE is
-- a reserved keyword in PostgreSQL (the British spelling of the ANALYZE
-- statistics command). A bare `analyse` identifier triggers a syntax error.
--
-- Existing rows have NULL until the next `npm run ingest:an` run.

alter table scrutins
  add column if not exists analyse_loi jsonb;
